package com.example.demo.controllers;

import com.example.demo.models.Review;
import com.example.demo.repositories.ReviewRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

@Controller // This means that this class is a Controller
@RequestMapping(path="/review") // This means URL's start with /demo (after Application path)
public class ReviewController {

    @Autowired
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReviewRepository reviewRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests

//    Integer index;
//    private String comment;
//    private String client;
//    private Date date;
//    private Integer rating;
//    private String location;
    public @ResponseBody String addNewReview (@RequestParam  int index, @RequestParam String comment,
                                              @RequestParam String client, @RequestParam Date date, @RequestParam int rating, @RequestParam String location) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Review n = new Review();
        n.setIndex(index);
        n.setComment(comment);
        n.setClient(client);
        n.setDate(date);
        n.setRating(rating);
        n.setLocation(location);
        reviewRepository.save(n);
        return "Saved";
    }




    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Review> getAllReviews() {
        // This returns a JSON or XML with the users
        return reviewRepository.findAll();
    }
}


//http://localhost:8080/review/all